// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Test.Subscriber.Infraestructure.Database;

#nullable disable

namespace Test.Subscriber.Infraestructure.Database.Migrations
{
    [DbContext(typeof(SubscriberDbContext))]
    partial class SubscriberDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Test.Subscriber.Core.Entitites.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_plan_id");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscriber");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriber_email");

                    b.HasIndex("SubscriptionPlanId")
                        .HasDatabaseName("ix_subscriber_subscription_plan_id");

                    b.ToTable("subscriber", (string)null);
                });

            modelBuilder.Entity("Test.Subscriber.Core.Entitites.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DaysToExpire")
                        .HasColumnType("integer")
                        .HasColumnName("days_to_expire");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monthly_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscription_plan");

                    b.ToTable("subscription_plan", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 16, 21, 3, 41, 951, DateTimeKind.Utc).AddTicks(826),
                            DaysToExpire = 30,
                            MonthlyPrice = 29.90m,
                            Name = "Basic",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 16, 21, 3, 41, 951, DateTimeKind.Utc).AddTicks(832),
                            DaysToExpire = 30,
                            MonthlyPrice = 59.90m,
                            Name = "Premium",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 16, 21, 3, 41, 951, DateTimeKind.Utc).AddTicks(835),
                            DaysToExpire = 30,
                            MonthlyPrice = 99.90m,
                            Name = "Enterprise",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Test.Subscriber.Core.Entitites.Subscriber", b =>
                {
                    b.HasOne("Test.Subscriber.Core.Entitites.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscribers")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriber_subscription_plan_subscription_plan_id");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Test.Subscriber.Core.Entitites.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscribers");
                });
#pragma warning restore 612, 618
        }
    }
}
